<?php
$books = array(
	0 => array('name' => "Heimvorteil", 
						'url' => "images/heimvorteil.jpg", 
						'price' => 9.99, 
						'author' => "Lotte Kinskofer", 
						'orderID' => 432423523,
						'stock' => 10),
	1 => array('name' => "Winterstarre", 
						'url' => "images/winterstarre.jpg", 
						'price' => 12.99, 
						'author' => "Joachim Rangnick", 
						'orderID' => 454646342,
						'stock' => 10),
	2 => array('name' => "Schwarze Brandung", 
						'url' => "images/schwarze_brandung.jpg", 
						'price' => 8.99, 
						'author' => "Sabine Weiss", 
						'orderID' => 497453713,
						'stock' => 10),
	3 => array('name' => "Der Schwarm", 
						'url' => "images/der_schwarm.jpg", 
						'price' => 14.99, 
						'author' => "Frank Schätzing", 
						'orderID' => 375475475,
						'stock' => 10),
	4 => array('name' => "Herr aller Dinge", 
						'url' => "images/herr_aller_dinge.jpg", 
						'price' => 12.99, 
						'author' => "Andreas Eschbach", 
						'orderID' => 312379334,
						'stock' => 10),
	5 => array('name' => "Die Bücherdiebin", 
						'url' => "images/die_buecherdiebin.jpg", 
						'price' => 9.99, 
						'author' => "Markus Zusak", 
						'orderID' => 374556432,
						'stock' => 10),
	6 => array('name' => "Die Seelenlosen", 
						'url' => "images/die_seelenlosen.jpg", 
						'price' => 13.99, 
						'author' => "Tanja Meurer", 
						'orderID' => 842523423,
						'stock' => 10),
	7 => array('name' => "Die Rabenkönigin", 
						'url' => "images/die_rabenkoenigin.jpg", 
						'price' => 8.99, 
						'author' => "Michelle N. Weber", 
						'orderID' => 832143689,
						'stock' => 10),
	8 => array('name' => "The Heir of Night", 
						'url' => "images/the_heir_of_night.jpg", 
						'price' => 13.99, 
						'author' => "Helen Lowe", 
						'orderID' => 823423557,
						'stock' => 10)
);
?>
